
cards= ('Ritual Beast Steeds(1)',
'1Ritual Beast Steeds(2)',
'3Ritual Beast Tamer Elder(1)',
'3Ritual Beast Tamer Elder(2)',
'3Ritual Beast Tamer Elder(3)',
'3Ritual Beast Tamer Elder(3)',
'3Ritual Beast Tamer Lara(1)',
'3Ritual Beast Tamer Lara(2)',
'3Ritual Beast Tamer Wen(1)',
'3Ritual Beast Tamer Wen(2)',
'3Spiritual Beast Apelio(1)',
'3Spiritual Beast Apelio(2)',
'3Spiritual Beast Cannahawk(1)',
'3Spiritual Beast Cannahawk(2)',
'3Spiritual Beast Cannahawk(3)',
'3Spiritual Beast Pettlephin(1)',
'3Spiritual Beast Rampengu(1)',
'3Spiritual Beast Rampengu(2)',
'3Spiritual Beast Rampengu(3)',
'2Book of Moon(1)',
'2Dimensional Fissure(1)',
'2Emergency Teleport(1)',
'2Emergency Teleport(2)',
'2Emergency Teleport(3)',
'2Foolish Burial(1)',
'2Gold Sarcophagus(1)',
'2twin twister(1)',
'2twin twister(2)',
'2twin twister(3)',
'2Raigeki(1)',
'2Snatch Steal(1)',
'1Bottomless Trap Hole(1)',
'3Macro Cosmos(1)',
'3Mind Crush(1)',
'3Mind Crush(2)',
'3Mind Crush(3)',
'3Ritual Beast Ambush(1)',
'3Ritual Beast Ambush(2)',
'3Ritual Beast Ambush(3)',
'3Ritual Beast Steeds(3)',
)

